language: rust
sudo: false
script:
- cargo build --verbose
- cargo test --verbose
- rustdoc --test src/lib.rs -L target
- cargo doc
after_success: ! '[ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]
  && echo ''<meta http-equiv=refresh content=0;url=compress/index.html>'' > target/doc/index.html
  && sudo pip install ghp-import && ghp-import -n target/doc && git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  gh-pages '
env:
  global:
  - secure: NcLf8VutE7aJ3Sq9IzksEM0qA4yfM+RJxAnD7zpA/y6ipsqtLfo1qUIiiNg7uhJjSGrGLd7fGH/awUDnJfhSYdKLRML87qFt02Dqz4E8gPIRUOe3a6Q2QHzvM/SiLsc6W/tRvHwKlHld0MzqHyrOWO6AMeIfV2+kREU3WbhPHtI=
notifications:
  email:
    on_success: never
